# Generated by Django 5.2.7 on 2026-05-21 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('description', models.TextField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('units', models.CharField(choices=[('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit')], max_length=10)),
                ('from_cache', models.BooleanField(default=False)),
            ],
        ),
    ]
